### ISSUE TITLE
getCakeBalance is not defined

### ISSUE THREAD

**Issue by rootisareservedword** [lmusarella/Pancakeswap-Prediction-Bot#4]
Hi, I'm attempting to run the bot with SIMULATION_MODE set to false, but I am receiving the following error:

Pancakeswap-Prediction-Bot/bot-lib/pcs-bot.module.js:145
  const balance = getCrypto() === BNB_CRYPTO ? await getBNBBalance() : await getCakeBalance();
                                                                       ^

ReferenceError: getCakeBalance is not defined
    at getPersonalBalance (/Pancakeswap-Prediction-Bot/bot-lib/pcs-bot.module.js:145:72)
    at startBotCommand (/Pancakeswap-Prediction-Bot/bot-lib/pcs-bot.module.js:63:25)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async init (/Pancakeswap-Prediction-Bot/bot-script/pcs-bot.js:25:3)

Any suggestions? Thanks!

**Comment by lmusarella** [comment]
Hi, thank you very much for reporting. I have fixed the error. Redownload and try again, it should work.

**Comment by rootisareservedword** [comment]
It's working now! Thank you! Great work!
