### ISSUE TITLE
Transaction Error

### ISSUE THREAD

**Issue by rootisareservedword** [lmusarella/Pancakeswap-Prediction-Bot#6]
Hi,

I am receiving the error below:

```
/bot-lib/common/print.module.js:170
    console.log("⛔ Transaction Error [", getConsoleTime(),"][", formatUnit(epoch),`][ ${exeption.code} ] =>`, errorMessage);
                                                                                                 ^

TypeError: Cannot read properties of undefined (reading 'code')
    at printTransactionError (/bot-lib/common/print.module.js:170:98)
    at betUp (/bot-lib/smart-contracts/pcs-prediction-smart-contract.module.js:81:5)
    at async betUpStrategy (/bot-lib/strategies/bet-strategy.module.js:26:49)
    at async executeBetUpCopyTradingStrategy (/bot-lib/strategies/copytrading-strategy.module.js:23:33)
    at async executeBetUpStrategy (/bot-lib/pcs-bot.module.js:88:10)
    at async FragmentRunningEvent.<anonymous> (/bot-script/pcs-bot.js:93:29)
```
I was running the bot with SIMULATION_MODE set to false when this error occurred.

**Comment by lmusarella** [comment]
Hi, thanks for the hint. Sometimes the errors returned by smart contracts are not always well defined. I released a fix that should have solved the problem.

**Comment by rootisareservedword** [comment]
That worked! Thanks again!
